// Generated by CIRCT firtool-1.62.0
module non_restoring_computation(
  input  [31:0] io_partial_remainder_in,
                io_divisor,
  output [31:0] io_partial_remainder_out
);

  assign io_partial_remainder_out =
    io_partial_remainder_in[31]
      ? io_partial_remainder_in + io_divisor
      : io_partial_remainder_in - io_divisor;
endmodule

module non_restoring_divider(
  input         clock,
                reset,
  output        io_dividend_ready,
  input         io_dividend_valid,
  input  [31:0] io_dividend_bits,
  output        io_divisor_ready,
  input         io_divisor_valid,
  input  [31:0] io_divisor_bits,
  input         io_quotient_ready,
  output        io_quotient_valid,
  output [31:0] io_quotient_bits,
  input         io_remainder_ready,
  output        io_remainder_valid,
  output [31:0] io_remainder_bits
);

  reg  [33:0] valid_reg;
  reg  [31:0] divisor_regs_0;
  reg  [31:0] divisor_regs_1;
  reg  [31:0] divisor_regs_2;
  reg  [31:0] divisor_regs_3;
  reg  [31:0] divisor_regs_4;
  reg  [31:0] divisor_regs_5;
  reg  [31:0] divisor_regs_6;
  reg  [31:0] divisor_regs_7;
  reg  [31:0] divisor_regs_8;
  reg  [31:0] divisor_regs_9;
  reg  [31:0] divisor_regs_10;
  reg  [31:0] divisor_regs_11;
  reg  [31:0] divisor_regs_12;
  reg  [31:0] divisor_regs_13;
  reg  [31:0] divisor_regs_14;
  reg  [31:0] divisor_regs_15;
  reg  [31:0] divisor_regs_16;
  reg  [31:0] divisor_regs_17;
  reg  [31:0] divisor_regs_18;
  reg  [31:0] divisor_regs_19;
  reg  [31:0] divisor_regs_20;
  reg  [31:0] divisor_regs_21;
  reg  [31:0] divisor_regs_22;
  reg  [31:0] divisor_regs_23;
  reg  [31:0] divisor_regs_24;
  reg  [31:0] divisor_regs_25;
  reg  [31:0] divisor_regs_26;
  reg  [31:0] divisor_regs_27;
  reg  [31:0] divisor_regs_28;
  reg  [31:0] divisor_regs_29;
  reg  [31:0] divisor_regs_30;
  reg  [31:0] divisor_regs_31;
  reg  [31:0] divisor_regs_32;
  reg  [31:0] dividend_regs_0;
  reg  [30:0] dividend_regs_1;
  reg  [29:0] dividend_regs_2;
  reg  [28:0] dividend_regs_3;
  reg  [27:0] dividend_regs_4;
  reg  [26:0] dividend_regs_5;
  reg  [25:0] dividend_regs_6;
  reg  [24:0] dividend_regs_7;
  reg  [23:0] dividend_regs_8;
  reg  [22:0] dividend_regs_9;
  reg  [21:0] dividend_regs_10;
  reg  [20:0] dividend_regs_11;
  reg  [19:0] dividend_regs_12;
  reg  [18:0] dividend_regs_13;
  reg  [17:0] dividend_regs_14;
  reg  [16:0] dividend_regs_15;
  reg  [15:0] dividend_regs_16;
  reg  [14:0] dividend_regs_17;
  reg  [13:0] dividend_regs_18;
  reg  [12:0] dividend_regs_19;
  reg  [11:0] dividend_regs_20;
  reg  [10:0] dividend_regs_21;
  reg  [9:0]  dividend_regs_22;
  reg  [8:0]  dividend_regs_23;
  reg  [7:0]  dividend_regs_24;
  reg  [6:0]  dividend_regs_25;
  reg  [5:0]  dividend_regs_26;
  reg  [4:0]  dividend_regs_27;
  reg  [3:0]  dividend_regs_28;
  reg  [2:0]  dividend_regs_29;
  reg  [1:0]  dividend_regs_30;
  reg         dividend_regs_31;
  reg         quotient_regs_0;
  reg  [1:0]  quotient_regs_1;
  reg  [2:0]  quotient_regs_2;
  reg  [3:0]  quotient_regs_3;
  reg  [4:0]  quotient_regs_4;
  reg  [5:0]  quotient_regs_5;
  reg  [6:0]  quotient_regs_6;
  reg  [7:0]  quotient_regs_7;
  reg  [8:0]  quotient_regs_8;
  reg  [9:0]  quotient_regs_9;
  reg  [10:0] quotient_regs_10;
  reg  [11:0] quotient_regs_11;
  reg  [12:0] quotient_regs_12;
  reg  [13:0] quotient_regs_13;
  reg  [14:0] quotient_regs_14;
  reg  [15:0] quotient_regs_15;
  reg  [16:0] quotient_regs_16;
  reg  [17:0] quotient_regs_17;
  reg  [18:0] quotient_regs_18;
  reg  [19:0] quotient_regs_19;
  reg  [20:0] quotient_regs_20;
  reg  [21:0] quotient_regs_21;
  reg  [22:0] quotient_regs_22;
  reg  [23:0] quotient_regs_23;
  reg  [24:0] quotient_regs_24;
  reg  [25:0] quotient_regs_25;
  reg  [26:0] quotient_regs_26;
  reg  [27:0] quotient_regs_27;
  reg  [28:0] quotient_regs_28;
  reg  [29:0] quotient_regs_29;
  reg  [30:0] quotient_regs_30;
  reg  [31:0] quotient_regs_31;
  reg  [31:0] partial_remainder_regs_0;
  reg  [31:0] partial_remainder_regs_1;
  reg  [31:0] partial_remainder_regs_2;
  reg  [31:0] partial_remainder_regs_3;
  reg  [31:0] partial_remainder_regs_4;
  reg  [31:0] partial_remainder_regs_5;
  reg  [31:0] partial_remainder_regs_6;
  reg  [31:0] partial_remainder_regs_7;
  reg  [31:0] partial_remainder_regs_8;
  reg  [31:0] partial_remainder_regs_9;
  reg  [31:0] partial_remainder_regs_10;
  reg  [31:0] partial_remainder_regs_11;
  reg  [31:0] partial_remainder_regs_12;
  reg  [31:0] partial_remainder_regs_13;
  reg  [31:0] partial_remainder_regs_14;
  reg  [31:0] partial_remainder_regs_15;
  reg  [31:0] partial_remainder_regs_16;
  reg  [31:0] partial_remainder_regs_17;
  reg  [31:0] partial_remainder_regs_18;
  reg  [31:0] partial_remainder_regs_19;
  reg  [31:0] partial_remainder_regs_20;
  reg  [31:0] partial_remainder_regs_21;
  reg  [31:0] partial_remainder_regs_22;
  reg  [31:0] partial_remainder_regs_23;
  reg  [31:0] partial_remainder_regs_24;
  reg  [31:0] partial_remainder_regs_25;
  reg  [31:0] partial_remainder_regs_26;
  reg  [31:0] partial_remainder_regs_27;
  reg  [31:0] partial_remainder_regs_28;
  reg  [31:0] partial_remainder_regs_29;
  reg  [31:0] partial_remainder_regs_30;
  reg  [31:0] partial_remainder_regs_31;
  reg  [31:0] partial_remainder_regs_32;
  wire [31:0] partial_remainder_outputs_0;
  wire [31:0] partial_remainder_outputs_1;
  wire [31:0] partial_remainder_outputs_2;
  wire [31:0] partial_remainder_outputs_3;
  wire [31:0] partial_remainder_outputs_4;
  wire [31:0] partial_remainder_outputs_5;
  wire [31:0] partial_remainder_outputs_6;
  wire [31:0] partial_remainder_outputs_7;
  wire [31:0] partial_remainder_outputs_8;
  wire [31:0] partial_remainder_outputs_9;
  wire [31:0] partial_remainder_outputs_10;
  wire [31:0] partial_remainder_outputs_11;
  wire [31:0] partial_remainder_outputs_12;
  wire [31:0] partial_remainder_outputs_13;
  wire [31:0] partial_remainder_outputs_14;
  wire [31:0] partial_remainder_outputs_15;
  wire [31:0] partial_remainder_outputs_16;
  wire [31:0] partial_remainder_outputs_17;
  wire [31:0] partial_remainder_outputs_18;
  wire [31:0] partial_remainder_outputs_19;
  wire [31:0] partial_remainder_outputs_20;
  wire [31:0] partial_remainder_outputs_21;
  wire [31:0] partial_remainder_outputs_22;
  wire [31:0] partial_remainder_outputs_23;
  wire [31:0] partial_remainder_outputs_24;
  wire [31:0] partial_remainder_outputs_25;
  wire [31:0] partial_remainder_outputs_26;
  wire [31:0] partial_remainder_outputs_27;
  wire [31:0] partial_remainder_outputs_28;
  wire [31:0] partial_remainder_outputs_29;
  wire [31:0] partial_remainder_outputs_30;
  wire [31:0] partial_remainder_outputs_31;
  always @(posedge clock) begin
    if (reset) begin
      valid_reg <= 34'h0;
      divisor_regs_0 <= 32'h0;
      divisor_regs_1 <= 32'h0;
      divisor_regs_2 <= 32'h0;
      divisor_regs_3 <= 32'h0;
      divisor_regs_4 <= 32'h0;
      divisor_regs_5 <= 32'h0;
      divisor_regs_6 <= 32'h0;
      divisor_regs_7 <= 32'h0;
      divisor_regs_8 <= 32'h0;
      divisor_regs_9 <= 32'h0;
      divisor_regs_10 <= 32'h0;
      divisor_regs_11 <= 32'h0;
      divisor_regs_12 <= 32'h0;
      divisor_regs_13 <= 32'h0;
      divisor_regs_14 <= 32'h0;
      divisor_regs_15 <= 32'h0;
      divisor_regs_16 <= 32'h0;
      divisor_regs_17 <= 32'h0;
      divisor_regs_18 <= 32'h0;
      divisor_regs_19 <= 32'h0;
      divisor_regs_20 <= 32'h0;
      divisor_regs_21 <= 32'h0;
      divisor_regs_22 <= 32'h0;
      divisor_regs_23 <= 32'h0;
      divisor_regs_24 <= 32'h0;
      divisor_regs_25 <= 32'h0;
      divisor_regs_26 <= 32'h0;
      divisor_regs_27 <= 32'h0;
      divisor_regs_28 <= 32'h0;
      divisor_regs_29 <= 32'h0;
      divisor_regs_30 <= 32'h0;
      divisor_regs_31 <= 32'h0;
      divisor_regs_32 <= 32'h0;
      dividend_regs_0 <= 32'h0;
      dividend_regs_1 <= 31'h0;
      dividend_regs_2 <= 30'h0;
      dividend_regs_3 <= 29'h0;
      dividend_regs_4 <= 28'h0;
      dividend_regs_5 <= 27'h0;
      dividend_regs_6 <= 26'h0;
      dividend_regs_7 <= 25'h0;
      dividend_regs_8 <= 24'h0;
      dividend_regs_9 <= 23'h0;
      dividend_regs_10 <= 22'h0;
      dividend_regs_11 <= 21'h0;
      dividend_regs_12 <= 20'h0;
      dividend_regs_13 <= 19'h0;
      dividend_regs_14 <= 18'h0;
      dividend_regs_15 <= 17'h0;
      dividend_regs_16 <= 16'h0;
      dividend_regs_17 <= 15'h0;
      dividend_regs_18 <= 14'h0;
      dividend_regs_19 <= 13'h0;
      dividend_regs_20 <= 12'h0;
      dividend_regs_21 <= 11'h0;
      dividend_regs_22 <= 10'h0;
      dividend_regs_23 <= 9'h0;
      dividend_regs_24 <= 8'h0;
      dividend_regs_25 <= 7'h0;
      dividend_regs_26 <= 6'h0;
      dividend_regs_27 <= 5'h0;
      dividend_regs_28 <= 4'h0;
      dividend_regs_29 <= 3'h0;
      dividend_regs_30 <= 2'h0;
      dividend_regs_31 <= 1'h0;
      quotient_regs_0 <= 1'h0;
      quotient_regs_1 <= 2'h0;
      quotient_regs_2 <= 3'h0;
      quotient_regs_3 <= 4'h0;
      quotient_regs_4 <= 5'h0;
      quotient_regs_5 <= 6'h0;
      quotient_regs_6 <= 7'h0;
      quotient_regs_7 <= 8'h0;
      quotient_regs_8 <= 9'h0;
      quotient_regs_9 <= 10'h0;
      quotient_regs_10 <= 11'h0;
      quotient_regs_11 <= 12'h0;
      quotient_regs_12 <= 13'h0;
      quotient_regs_13 <= 14'h0;
      quotient_regs_14 <= 15'h0;
      quotient_regs_15 <= 16'h0;
      quotient_regs_16 <= 17'h0;
      quotient_regs_17 <= 18'h0;
      quotient_regs_18 <= 19'h0;
      quotient_regs_19 <= 20'h0;
      quotient_regs_20 <= 21'h0;
      quotient_regs_21 <= 22'h0;
      quotient_regs_22 <= 23'h0;
      quotient_regs_23 <= 24'h0;
      quotient_regs_24 <= 25'h0;
      quotient_regs_25 <= 26'h0;
      quotient_regs_26 <= 27'h0;
      quotient_regs_27 <= 28'h0;
      quotient_regs_28 <= 29'h0;
      quotient_regs_29 <= 30'h0;
      quotient_regs_30 <= 31'h0;
      quotient_regs_31 <= 32'h0;
      partial_remainder_regs_0 <= 32'h0;
      partial_remainder_regs_1 <= 32'h0;
      partial_remainder_regs_2 <= 32'h0;
      partial_remainder_regs_3 <= 32'h0;
      partial_remainder_regs_4 <= 32'h0;
      partial_remainder_regs_5 <= 32'h0;
      partial_remainder_regs_6 <= 32'h0;
      partial_remainder_regs_7 <= 32'h0;
      partial_remainder_regs_8 <= 32'h0;
      partial_remainder_regs_9 <= 32'h0;
      partial_remainder_regs_10 <= 32'h0;
      partial_remainder_regs_11 <= 32'h0;
      partial_remainder_regs_12 <= 32'h0;
      partial_remainder_regs_13 <= 32'h0;
      partial_remainder_regs_14 <= 32'h0;
      partial_remainder_regs_15 <= 32'h0;
      partial_remainder_regs_16 <= 32'h0;
      partial_remainder_regs_17 <= 32'h0;
      partial_remainder_regs_18 <= 32'h0;
      partial_remainder_regs_19 <= 32'h0;
      partial_remainder_regs_20 <= 32'h0;
      partial_remainder_regs_21 <= 32'h0;
      partial_remainder_regs_22 <= 32'h0;
      partial_remainder_regs_23 <= 32'h0;
      partial_remainder_regs_24 <= 32'h0;
      partial_remainder_regs_25 <= 32'h0;
      partial_remainder_regs_26 <= 32'h0;
      partial_remainder_regs_27 <= 32'h0;
      partial_remainder_regs_28 <= 32'h0;
      partial_remainder_regs_29 <= 32'h0;
      partial_remainder_regs_30 <= 32'h0;
      partial_remainder_regs_31 <= 32'h0;
      partial_remainder_regs_32 <= 32'h0;
    end
    else begin
      valid_reg <= {valid_reg[32:0], io_dividend_valid & io_divisor_valid};
      divisor_regs_0 <= io_divisor_bits;
      divisor_regs_1 <= divisor_regs_0;
      divisor_regs_2 <= divisor_regs_1;
      divisor_regs_3 <= divisor_regs_2;
      divisor_regs_4 <= divisor_regs_3;
      divisor_regs_5 <= divisor_regs_4;
      divisor_regs_6 <= divisor_regs_5;
      divisor_regs_7 <= divisor_regs_6;
      divisor_regs_8 <= divisor_regs_7;
      divisor_regs_9 <= divisor_regs_8;
      divisor_regs_10 <= divisor_regs_9;
      divisor_regs_11 <= divisor_regs_10;
      divisor_regs_12 <= divisor_regs_11;
      divisor_regs_13 <= divisor_regs_12;
      divisor_regs_14 <= divisor_regs_13;
      divisor_regs_15 <= divisor_regs_14;
      divisor_regs_16 <= divisor_regs_15;
      divisor_regs_17 <= divisor_regs_16;
      divisor_regs_18 <= divisor_regs_17;
      divisor_regs_19 <= divisor_regs_18;
      divisor_regs_20 <= divisor_regs_19;
      divisor_regs_21 <= divisor_regs_20;
      divisor_regs_22 <= divisor_regs_21;
      divisor_regs_23 <= divisor_regs_22;
      divisor_regs_24 <= divisor_regs_23;
      divisor_regs_25 <= divisor_regs_24;
      divisor_regs_26 <= divisor_regs_25;
      divisor_regs_27 <= divisor_regs_26;
      divisor_regs_28 <= divisor_regs_27;
      divisor_regs_29 <= divisor_regs_28;
      divisor_regs_30 <= divisor_regs_29;
      divisor_regs_31 <= divisor_regs_30;
      divisor_regs_32 <= divisor_regs_31;
      dividend_regs_0 <= io_dividend_bits;
      dividend_regs_1 <= dividend_regs_0[30:0];
      dividend_regs_2 <= dividend_regs_1[29:0];
      dividend_regs_3 <= dividend_regs_2[28:0];
      dividend_regs_4 <= dividend_regs_3[27:0];
      dividend_regs_5 <= dividend_regs_4[26:0];
      dividend_regs_6 <= dividend_regs_5[25:0];
      dividend_regs_7 <= dividend_regs_6[24:0];
      dividend_regs_8 <= dividend_regs_7[23:0];
      dividend_regs_9 <= dividend_regs_8[22:0];
      dividend_regs_10 <= dividend_regs_9[21:0];
      dividend_regs_11 <= dividend_regs_10[20:0];
      dividend_regs_12 <= dividend_regs_11[19:0];
      dividend_regs_13 <= dividend_regs_12[18:0];
      dividend_regs_14 <= dividend_regs_13[17:0];
      dividend_regs_15 <= dividend_regs_14[16:0];
      dividend_regs_16 <= dividend_regs_15[15:0];
      dividend_regs_17 <= dividend_regs_16[14:0];
      dividend_regs_18 <= dividend_regs_17[13:0];
      dividend_regs_19 <= dividend_regs_18[12:0];
      dividend_regs_20 <= dividend_regs_19[11:0];
      dividend_regs_21 <= dividend_regs_20[10:0];
      dividend_regs_22 <= dividend_regs_21[9:0];
      dividend_regs_23 <= dividend_regs_22[8:0];
      dividend_regs_24 <= dividend_regs_23[7:0];
      dividend_regs_25 <= dividend_regs_24[6:0];
      dividend_regs_26 <= dividend_regs_25[5:0];
      dividend_regs_27 <= dividend_regs_26[4:0];
      dividend_regs_28 <= dividend_regs_27[3:0];
      dividend_regs_29 <= dividend_regs_28[2:0];
      dividend_regs_30 <= dividend_regs_29[1:0];
      dividend_regs_31 <= dividend_regs_30[0];
      quotient_regs_1 <= {quotient_regs_0, ~(partial_remainder_outputs_1[31])};
      quotient_regs_2 <= {quotient_regs_1, ~(partial_remainder_outputs_2[31])};
      quotient_regs_3 <= {quotient_regs_2, ~(partial_remainder_outputs_3[31])};
      quotient_regs_4 <= {quotient_regs_3, ~(partial_remainder_outputs_4[31])};
      quotient_regs_5 <= {quotient_regs_4, ~(partial_remainder_outputs_5[31])};
      quotient_regs_6 <= {quotient_regs_5, ~(partial_remainder_outputs_6[31])};
      quotient_regs_7 <= {quotient_regs_6, ~(partial_remainder_outputs_7[31])};
      quotient_regs_8 <= {quotient_regs_7, ~(partial_remainder_outputs_8[31])};
      quotient_regs_9 <= {quotient_regs_8, ~(partial_remainder_outputs_9[31])};
      quotient_regs_10 <= {quotient_regs_9, ~(partial_remainder_outputs_10[31])};
      quotient_regs_11 <= {quotient_regs_10, ~(partial_remainder_outputs_11[31])};
      quotient_regs_12 <= {quotient_regs_11, ~(partial_remainder_outputs_12[31])};
      quotient_regs_13 <= {quotient_regs_12, ~(partial_remainder_outputs_13[31])};
      quotient_regs_14 <= {quotient_regs_13, ~(partial_remainder_outputs_14[31])};
      quotient_regs_15 <= {quotient_regs_14, ~(partial_remainder_outputs_15[31])};
      quotient_regs_16 <= {quotient_regs_15, ~(partial_remainder_outputs_16[31])};
      quotient_regs_17 <= {quotient_regs_16, ~(partial_remainder_outputs_17[31])};
      quotient_regs_18 <= {quotient_regs_17, ~(partial_remainder_outputs_18[31])};
      quotient_regs_19 <= {quotient_regs_18, ~(partial_remainder_outputs_19[31])};
      quotient_regs_20 <= {quotient_regs_19, ~(partial_remainder_outputs_20[31])};
      quotient_regs_21 <= {quotient_regs_20, ~(partial_remainder_outputs_21[31])};
      quotient_regs_22 <= {quotient_regs_21, ~(partial_remainder_outputs_22[31])};
      quotient_regs_23 <= {quotient_regs_22, ~(partial_remainder_outputs_23[31])};
      quotient_regs_24 <= {quotient_regs_23, ~(partial_remainder_outputs_24[31])};
      quotient_regs_25 <= {quotient_regs_24, ~(partial_remainder_outputs_25[31])};
      quotient_regs_26 <= {quotient_regs_25, ~(partial_remainder_outputs_26[31])};
      quotient_regs_27 <= {quotient_regs_26, ~(partial_remainder_outputs_27[31])};
      quotient_regs_28 <= {quotient_regs_27, ~(partial_remainder_outputs_28[31])};
      quotient_regs_29 <= {quotient_regs_28, ~(partial_remainder_outputs_29[31])};
      quotient_regs_30 <= {quotient_regs_29, ~(partial_remainder_outputs_30[31])};
      quotient_regs_31 <= {quotient_regs_30, ~(partial_remainder_outputs_31[31])};
      partial_remainder_regs_0 <= {31'h0, dividend_regs_0[31]};
      partial_remainder_regs_1 <=
        {partial_remainder_outputs_0[30:0], dividend_regs_1[30]};
      partial_remainder_regs_2 <=
        {partial_remainder_outputs_1[30:0], dividend_regs_2[29]};
      partial_remainder_regs_3 <=
        {partial_remainder_outputs_2[30:0], dividend_regs_3[28]};
      partial_remainder_regs_4 <=
        {partial_remainder_outputs_3[30:0], dividend_regs_4[27]};
      partial_remainder_regs_5 <=
        {partial_remainder_outputs_4[30:0], dividend_regs_5[26]};
      partial_remainder_regs_6 <=
        {partial_remainder_outputs_5[30:0], dividend_regs_6[25]};
      partial_remainder_regs_7 <=
        {partial_remainder_outputs_6[30:0], dividend_regs_7[24]};
      partial_remainder_regs_8 <=
        {partial_remainder_outputs_7[30:0], dividend_regs_8[23]};
      partial_remainder_regs_9 <=
        {partial_remainder_outputs_8[30:0], dividend_regs_9[22]};
      partial_remainder_regs_10 <=
        {partial_remainder_outputs_9[30:0], dividend_regs_10[21]};
      partial_remainder_regs_11 <=
        {partial_remainder_outputs_10[30:0], dividend_regs_11[20]};
      partial_remainder_regs_12 <=
        {partial_remainder_outputs_11[30:0], dividend_regs_12[19]};
      partial_remainder_regs_13 <=
        {partial_remainder_outputs_12[30:0], dividend_regs_13[18]};
      partial_remainder_regs_14 <=
        {partial_remainder_outputs_13[30:0], dividend_regs_14[17]};
      partial_remainder_regs_15 <=
        {partial_remainder_outputs_14[30:0], dividend_regs_15[16]};
      partial_remainder_regs_16 <=
        {partial_remainder_outputs_15[30:0], dividend_regs_16[15]};
      partial_remainder_regs_17 <=
        {partial_remainder_outputs_16[30:0], dividend_regs_17[14]};
      partial_remainder_regs_18 <=
        {partial_remainder_outputs_17[30:0], dividend_regs_18[13]};
      partial_remainder_regs_19 <=
        {partial_remainder_outputs_18[30:0], dividend_regs_19[12]};
      partial_remainder_regs_20 <=
        {partial_remainder_outputs_19[30:0], dividend_regs_20[11]};
      partial_remainder_regs_21 <=
        {partial_remainder_outputs_20[30:0], dividend_regs_21[10]};
      partial_remainder_regs_22 <=
        {partial_remainder_outputs_21[30:0], dividend_regs_22[9]};
      partial_remainder_regs_23 <=
        {partial_remainder_outputs_22[30:0], dividend_regs_23[8]};
      partial_remainder_regs_24 <=
        {partial_remainder_outputs_23[30:0], dividend_regs_24[7]};
      partial_remainder_regs_25 <=
        {partial_remainder_outputs_24[30:0], dividend_regs_25[6]};
      partial_remainder_regs_26 <=
        {partial_remainder_outputs_25[30:0], dividend_regs_26[5]};
      partial_remainder_regs_27 <=
        {partial_remainder_outputs_26[30:0], dividend_regs_27[4]};
      partial_remainder_regs_28 <=
        {partial_remainder_outputs_27[30:0], dividend_regs_28[3]};
      partial_remainder_regs_29 <=
        {partial_remainder_outputs_28[30:0], dividend_regs_29[2]};
      partial_remainder_regs_30 <=
        {partial_remainder_outputs_29[30:0], dividend_regs_30[1]};
      partial_remainder_regs_31 <= {partial_remainder_outputs_30[30:0], dividend_regs_31};
      partial_remainder_regs_32 <= partial_remainder_outputs_31;
    end
  end // always @(posedge)
  non_restoring_computation non_restoring_dividers_non_restoring_computation (
    .io_partial_remainder_in  (partial_remainder_regs_0),
    .io_divisor               (divisor_regs_1),
    .io_partial_remainder_out (partial_remainder_outputs_0)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_1 (
    .io_partial_remainder_in  (partial_remainder_regs_1),
    .io_divisor               (divisor_regs_2),
    .io_partial_remainder_out (partial_remainder_outputs_1)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_2 (
    .io_partial_remainder_in  (partial_remainder_regs_2),
    .io_divisor               (divisor_regs_3),
    .io_partial_remainder_out (partial_remainder_outputs_2)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_3 (
    .io_partial_remainder_in  (partial_remainder_regs_3),
    .io_divisor               (divisor_regs_4),
    .io_partial_remainder_out (partial_remainder_outputs_3)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_4 (
    .io_partial_remainder_in  (partial_remainder_regs_4),
    .io_divisor               (divisor_regs_5),
    .io_partial_remainder_out (partial_remainder_outputs_4)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_5 (
    .io_partial_remainder_in  (partial_remainder_regs_5),
    .io_divisor               (divisor_regs_6),
    .io_partial_remainder_out (partial_remainder_outputs_5)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_6 (
    .io_partial_remainder_in  (partial_remainder_regs_6),
    .io_divisor               (divisor_regs_7),
    .io_partial_remainder_out (partial_remainder_outputs_6)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_7 (
    .io_partial_remainder_in  (partial_remainder_regs_7),
    .io_divisor               (divisor_regs_8),
    .io_partial_remainder_out (partial_remainder_outputs_7)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_8 (
    .io_partial_remainder_in  (partial_remainder_regs_8),
    .io_divisor               (divisor_regs_9),
    .io_partial_remainder_out (partial_remainder_outputs_8)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_9 (
    .io_partial_remainder_in  (partial_remainder_regs_9),
    .io_divisor               (divisor_regs_10),
    .io_partial_remainder_out (partial_remainder_outputs_9)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_10 (
    .io_partial_remainder_in  (partial_remainder_regs_10),
    .io_divisor               (divisor_regs_11),
    .io_partial_remainder_out (partial_remainder_outputs_10)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_11 (
    .io_partial_remainder_in  (partial_remainder_regs_11),
    .io_divisor               (divisor_regs_12),
    .io_partial_remainder_out (partial_remainder_outputs_11)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_12 (
    .io_partial_remainder_in  (partial_remainder_regs_12),
    .io_divisor               (divisor_regs_13),
    .io_partial_remainder_out (partial_remainder_outputs_12)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_13 (
    .io_partial_remainder_in  (partial_remainder_regs_13),
    .io_divisor               (divisor_regs_14),
    .io_partial_remainder_out (partial_remainder_outputs_13)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_14 (
    .io_partial_remainder_in  (partial_remainder_regs_14),
    .io_divisor               (divisor_regs_15),
    .io_partial_remainder_out (partial_remainder_outputs_14)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_15 (
    .io_partial_remainder_in  (partial_remainder_regs_15),
    .io_divisor               (divisor_regs_16),
    .io_partial_remainder_out (partial_remainder_outputs_15)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_16 (
    .io_partial_remainder_in  (partial_remainder_regs_16),
    .io_divisor               (divisor_regs_17),
    .io_partial_remainder_out (partial_remainder_outputs_16)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_17 (
    .io_partial_remainder_in  (partial_remainder_regs_17),
    .io_divisor               (divisor_regs_18),
    .io_partial_remainder_out (partial_remainder_outputs_17)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_18 (
    .io_partial_remainder_in  (partial_remainder_regs_18),
    .io_divisor               (divisor_regs_19),
    .io_partial_remainder_out (partial_remainder_outputs_18)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_19 (
    .io_partial_remainder_in  (partial_remainder_regs_19),
    .io_divisor               (divisor_regs_20),
    .io_partial_remainder_out (partial_remainder_outputs_19)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_20 (
    .io_partial_remainder_in  (partial_remainder_regs_20),
    .io_divisor               (divisor_regs_21),
    .io_partial_remainder_out (partial_remainder_outputs_20)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_21 (
    .io_partial_remainder_in  (partial_remainder_regs_21),
    .io_divisor               (divisor_regs_22),
    .io_partial_remainder_out (partial_remainder_outputs_21)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_22 (
    .io_partial_remainder_in  (partial_remainder_regs_22),
    .io_divisor               (divisor_regs_23),
    .io_partial_remainder_out (partial_remainder_outputs_22)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_23 (
    .io_partial_remainder_in  (partial_remainder_regs_23),
    .io_divisor               (divisor_regs_24),
    .io_partial_remainder_out (partial_remainder_outputs_23)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_24 (
    .io_partial_remainder_in  (partial_remainder_regs_24),
    .io_divisor               (divisor_regs_25),
    .io_partial_remainder_out (partial_remainder_outputs_24)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_25 (
    .io_partial_remainder_in  (partial_remainder_regs_25),
    .io_divisor               (divisor_regs_26),
    .io_partial_remainder_out (partial_remainder_outputs_25)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_26 (
    .io_partial_remainder_in  (partial_remainder_regs_26),
    .io_divisor               (divisor_regs_27),
    .io_partial_remainder_out (partial_remainder_outputs_26)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_27 (
    .io_partial_remainder_in  (partial_remainder_regs_27),
    .io_divisor               (divisor_regs_28),
    .io_partial_remainder_out (partial_remainder_outputs_27)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_28 (
    .io_partial_remainder_in  (partial_remainder_regs_28),
    .io_divisor               (divisor_regs_29),
    .io_partial_remainder_out (partial_remainder_outputs_28)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_29 (
    .io_partial_remainder_in  (partial_remainder_regs_29),
    .io_divisor               (divisor_regs_30),
    .io_partial_remainder_out (partial_remainder_outputs_29)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_30 (
    .io_partial_remainder_in  (partial_remainder_regs_30),
    .io_divisor               (divisor_regs_31),
    .io_partial_remainder_out (partial_remainder_outputs_30)
  );
  non_restoring_computation non_restoring_dividers_non_restoring_computation_31 (
    .io_partial_remainder_in  (partial_remainder_regs_31),
    .io_divisor               (divisor_regs_32),
    .io_partial_remainder_out (partial_remainder_outputs_31)
  );
  assign io_dividend_ready = 1'h1;
  assign io_divisor_ready = 1'h1;
  assign io_quotient_valid = valid_reg[33];
  assign io_quotient_bits = quotient_regs_31;
  assign io_remainder_valid = valid_reg[33];
  assign io_remainder_bits = partial_remainder_regs_32;
endmodule

