// Generated by CIRCT firtool-1.76.0
module Arbiter2_FU_output(	// src/main/scala/chisel3/util/Arbiter.scala:133:7
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [6:0]  io_in_0_bits_RD,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [31:0] io_in_0_bits_RD_data,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_RD_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [6:0]  io_in_1_bits_RD,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [31:0] io_in_1_bits_RD_data,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_RD_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [6:0]  io_out_bits_RD,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [31:0] io_out_bits_RD_data,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_RD_valid	// src/main/scala/chisel3/util/Arbiter.scala:140:14
);

  assign io_in_1_ready = ~io_in_0_valid;	// src/main/scala/chisel3/util/Arbiter.scala:45:78, :133:7
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :154:31
  assign io_out_bits_RD = io_in_0_valid ? io_in_0_bits_RD : io_in_1_bits_RD;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_RD_data =
    io_in_0_valid ? io_in_0_bits_RD_data : io_in_1_bits_RD_data;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_RD_valid =
    io_in_0_valid ? io_in_0_bits_RD_valid : io_in_1_bits_RD_valid;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
endmodule

