// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// VCS coverage exclude_file
module mem_64x2(
  input  [5:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [1:0] R0_data,
  input  [5:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [1:0] W0_data,
               W0_mask,
  input  [5:0] W1_addr,
  input        W1_en,
               W1_clk,
  input  [1:0] W1_data,
               W1_mask,
  input  [5:0] W2_addr,
  input        W2_en,
               W2_clk,
  input  [1:0] W2_data,
               W2_mask,
  input  [5:0] W3_addr,
  input        W3_en,
               W3_clk,
  input  [1:0] W3_data,
               W3_mask,
  input  [5:0] W4_addr,
  input        W4_en,
               W4_clk,
  input  [1:0] W4_data,
               W4_mask
);

  reg [1:0] Memory[0:63];
  reg       _R0_en_d0;
  reg [5:0] _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & W0_mask[0])
      Memory[W0_addr][32'h0 +: 1] <= W0_data[0];
    if (W0_en & W0_mask[1])
      Memory[W0_addr][32'h1 +: 1] <= W0_data[1];
    if (W1_en & W1_mask[0])
      Memory[W1_addr][32'h0 +: 1] <= W1_data[0];
    if (W1_en & W1_mask[1])
      Memory[W1_addr][32'h1 +: 1] <= W1_data[1];
    if (W2_en & W2_mask[0])
      Memory[W2_addr][32'h0 +: 1] <= W2_data[0];
    if (W2_en & W2_mask[1])
      Memory[W2_addr][32'h1 +: 1] <= W2_data[1];
    if (W3_en & W3_mask[0])
      Memory[W3_addr][32'h0 +: 1] <= W3_data[0];
    if (W3_en & W3_mask[1])
      Memory[W3_addr][32'h1 +: 1] <= W3_data[1];
    if (W4_en & W4_mask[0])
      Memory[W4_addr][32'h0 +: 1] <= W4_data[0];
    if (W4_en & W4_mask[1])
      Memory[W4_addr][32'h1 +: 1] <= W4_data[1];
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 2'bx;
endmodule

