// Generated by CIRCT firtool-1.76.0

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PHT_memory(	// src/main/scala/Frontend/BP/gshare.scala:39:7
  input         clock,	// src/main/scala/Frontend/BP/gshare.scala:39:7
  input  [15:0] io_addrA,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  output [15:0] io_readDataA,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  input  [15:0] io_addrB,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  output [15:0] io_readDataB,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  input  [15:0] io_addrC,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  input  [1:0]  io_writeDataC,	// src/main/scala/Frontend/BP/gshare.scala:43:14
  input         io_writeEnableC	// src/main/scala/Frontend/BP/gshare.scala:43:14
);

  wire [1:0] _mem_ext_R0_data;	// src/main/scala/Frontend/BP/gshare.scala:59:24
  wire [1:0] _mem_ext_R1_data;	// src/main/scala/Frontend/BP/gshare.scala:59:24
  mem_65536x2 mem_ext (	// src/main/scala/Frontend/BP/gshare.scala:59:24
    .R0_addr (io_addrB),
    .R0_en   (1'h1),	// src/main/scala/Frontend/BP/gshare.scala:39:7
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .R1_addr (io_addrA),
    .R1_en   (1'h1),	// src/main/scala/Frontend/BP/gshare.scala:39:7
    .R1_clk  (clock),
    .R1_data (_mem_ext_R1_data),
    .W0_addr (io_addrC),
    .W0_en   (io_writeEnableC),
    .W0_clk  (clock),
    .W0_data (io_writeDataC)
  );	// src/main/scala/Frontend/BP/gshare.scala:59:24
  assign io_readDataA = {14'h0, _mem_ext_R1_data};	// src/main/scala/Frontend/BP/gshare.scala:39:7, :59:24, :61:16
  assign io_readDataB = {14'h0, _mem_ext_R0_data};	// src/main/scala/Frontend/BP/gshare.scala:39:7, :59:24, :61:16, :62:16
endmodule

