// Generated by CIRCT firtool-1.76.0
module Queue2_FTQ_entry(
  input         clock,
                reset,
                io_enq_valid,
                io_enq_bits_valid,
  input  [31:0] io_enq_bits_fetch_PC,
  input         io_enq_bits_is_misprediction,
  input  [31:0] io_enq_bits_predicted_PC,
  input  [5:0]  io_enq_bits_ROB_index,
  input         io_enq_bits_T_NT,
  input  [2:0]  io_enq_bits_br_type,
  input  [1:0]  io_enq_bits_dominant_index,
  input  [31:0] io_enq_bits_resolved_PC,
  input         io_deq_ready,
  output        io_deq_valid,
                io_deq_bits_valid,
  output [31:0] io_deq_bits_fetch_PC,
  output        io_deq_bits_is_misprediction,
  output [31:0] io_deq_bits_predicted_PC,
  output [5:0]  io_deq_bits_ROB_index,
  output        io_deq_bits_T_NT,
  output [2:0]  io_deq_bits_br_type,
  output [1:0]  io_deq_bits_dominant_index,
  output [31:0] io_deq_bits_resolved_PC,
  input         io_flush
);

  wire         io_enq_ready;
  wire [109:0] _ram_ext_R0_data;
  reg          wrap;
  reg          wrap_1;
  reg          maybe_full;
  wire         ptr_match = wrap == wrap_1;
  wire         empty = ptr_match & ~maybe_full;
  wire         do_enq = io_enq_ready & io_enq_valid;
  assign io_enq_ready = ~(ptr_match & maybe_full);
  always @(posedge clock) begin
    if (reset) begin
      wrap <= 1'h0;
      wrap_1 <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      wrap <= ~io_flush & (do_enq ? wrap - 1'h1 : wrap);
      wrap_1 <= ~io_flush & (do_deq ? wrap_1 - 1'h1 : wrap_1);
      maybe_full <= ~io_flush & (do_enq == do_deq ? maybe_full : do_enq);
    end
  end // always @(posedge)
  ram_2x110 ram_ext (
    .R0_addr (wrap_1),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_resolved_PC,
        io_enq_bits_dominant_index,
        io_enq_bits_br_type,
        io_enq_bits_T_NT,
        io_enq_bits_ROB_index,
        io_enq_bits_predicted_PC,
        io_enq_bits_is_misprediction,
        io_enq_bits_fetch_PC,
        io_enq_bits_valid})
  );
  assign io_deq_valid = ~empty;
  assign io_deq_bits_valid = _ram_ext_R0_data[0];
  assign io_deq_bits_fetch_PC = _ram_ext_R0_data[32:1];
  assign io_deq_bits_is_misprediction = _ram_ext_R0_data[33];
  assign io_deq_bits_predicted_PC = _ram_ext_R0_data[65:34];
  assign io_deq_bits_ROB_index = _ram_ext_R0_data[71:66];
  assign io_deq_bits_T_NT = _ram_ext_R0_data[72];
  assign io_deq_bits_br_type = _ram_ext_R0_data[75:73];
  assign io_deq_bits_dominant_index = _ram_ext_R0_data[77:76];
  assign io_deq_bits_resolved_PC = _ram_ext_R0_data[109:78];
endmodule

