// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Queue1_final_AXI_response(
  input          clock,
                 reset,
                 io_enq_valid,
  input  [255:0] io_enq_bits_data,
  input  [7:0]   io_enq_bits_ID,
  input          io_deq_ready,
  output         io_deq_valid,
  output [255:0] io_deq_bits_data,
  output [7:0]   io_deq_bits_ID
);

  reg  [263:0] ram;
  reg          full;
  wire         io_deq_valid_0 = io_enq_valid | full;
  wire         do_enq = ~(~full & io_deq_ready) & ~full & io_enq_valid;
  always @(posedge clock) begin
    if (do_enq)
      ram <= {io_enq_bits_ID, io_enq_bits_data};
    if (reset)
      full <= 1'h0;
    else if (~(do_enq == (full & io_deq_ready & io_deq_valid_0)))
      full <= do_enq;
  end // always @(posedge)
  assign io_deq_valid = io_deq_valid_0;
  assign io_deq_bits_data = full ? ram[255:0] : io_enq_bits_data;
  assign io_deq_bits_ID = full ? ram[263:256] : io_enq_bits_ID;
endmodule

