// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// VCS coverage exclude_file
module ram_16x110(
  input  [3:0]   R0_addr,
  input          R0_en,
                 R0_clk,
  output [109:0] R0_data,
  input  [3:0]   W0_addr,
  input          W0_en,
                 W0_clk,
  input  [109:0] W0_data,
                 W0_mask
);

  reg [109:0] Memory[0:15];
  reg         _R0_en_d0;
  reg [3:0]   _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & W0_mask[0])
      Memory[W0_addr][32'h0 +: 1] <= W0_data[0];
    if (W0_en & W0_mask[1])
      Memory[W0_addr][32'h1 +: 1] <= W0_data[1];
    if (W0_en & W0_mask[2])
      Memory[W0_addr][32'h2 +: 1] <= W0_data[2];
    if (W0_en & W0_mask[3])
      Memory[W0_addr][32'h3 +: 1] <= W0_data[3];
    if (W0_en & W0_mask[4])
      Memory[W0_addr][32'h4 +: 1] <= W0_data[4];
    if (W0_en & W0_mask[5])
      Memory[W0_addr][32'h5 +: 1] <= W0_data[5];
    if (W0_en & W0_mask[6])
      Memory[W0_addr][32'h6 +: 1] <= W0_data[6];
    if (W0_en & W0_mask[7])
      Memory[W0_addr][32'h7 +: 1] <= W0_data[7];
    if (W0_en & W0_mask[8])
      Memory[W0_addr][32'h8 +: 1] <= W0_data[8];
    if (W0_en & W0_mask[9])
      Memory[W0_addr][32'h9 +: 1] <= W0_data[9];
    if (W0_en & W0_mask[10])
      Memory[W0_addr][32'hA +: 1] <= W0_data[10];
    if (W0_en & W0_mask[11])
      Memory[W0_addr][32'hB +: 1] <= W0_data[11];
    if (W0_en & W0_mask[12])
      Memory[W0_addr][32'hC +: 1] <= W0_data[12];
    if (W0_en & W0_mask[13])
      Memory[W0_addr][32'hD +: 1] <= W0_data[13];
    if (W0_en & W0_mask[14])
      Memory[W0_addr][32'hE +: 1] <= W0_data[14];
    if (W0_en & W0_mask[15])
      Memory[W0_addr][32'hF +: 1] <= W0_data[15];
    if (W0_en & W0_mask[16])
      Memory[W0_addr][32'h10 +: 1] <= W0_data[16];
    if (W0_en & W0_mask[17])
      Memory[W0_addr][32'h11 +: 1] <= W0_data[17];
    if (W0_en & W0_mask[18])
      Memory[W0_addr][32'h12 +: 1] <= W0_data[18];
    if (W0_en & W0_mask[19])
      Memory[W0_addr][32'h13 +: 1] <= W0_data[19];
    if (W0_en & W0_mask[20])
      Memory[W0_addr][32'h14 +: 1] <= W0_data[20];
    if (W0_en & W0_mask[21])
      Memory[W0_addr][32'h15 +: 1] <= W0_data[21];
    if (W0_en & W0_mask[22])
      Memory[W0_addr][32'h16 +: 1] <= W0_data[22];
    if (W0_en & W0_mask[23])
      Memory[W0_addr][32'h17 +: 1] <= W0_data[23];
    if (W0_en & W0_mask[24])
      Memory[W0_addr][32'h18 +: 1] <= W0_data[24];
    if (W0_en & W0_mask[25])
      Memory[W0_addr][32'h19 +: 1] <= W0_data[25];
    if (W0_en & W0_mask[26])
      Memory[W0_addr][32'h1A +: 1] <= W0_data[26];
    if (W0_en & W0_mask[27])
      Memory[W0_addr][32'h1B +: 1] <= W0_data[27];
    if (W0_en & W0_mask[28])
      Memory[W0_addr][32'h1C +: 1] <= W0_data[28];
    if (W0_en & W0_mask[29])
      Memory[W0_addr][32'h1D +: 1] <= W0_data[29];
    if (W0_en & W0_mask[30])
      Memory[W0_addr][32'h1E +: 1] <= W0_data[30];
    if (W0_en & W0_mask[31])
      Memory[W0_addr][32'h1F +: 1] <= W0_data[31];
    if (W0_en & W0_mask[32])
      Memory[W0_addr][32'h20 +: 1] <= W0_data[32];
    if (W0_en & W0_mask[33])
      Memory[W0_addr][32'h21 +: 1] <= W0_data[33];
    if (W0_en & W0_mask[34])
      Memory[W0_addr][32'h22 +: 1] <= W0_data[34];
    if (W0_en & W0_mask[35])
      Memory[W0_addr][32'h23 +: 1] <= W0_data[35];
    if (W0_en & W0_mask[36])
      Memory[W0_addr][32'h24 +: 1] <= W0_data[36];
    if (W0_en & W0_mask[37])
      Memory[W0_addr][32'h25 +: 1] <= W0_data[37];
    if (W0_en & W0_mask[38])
      Memory[W0_addr][32'h26 +: 1] <= W0_data[38];
    if (W0_en & W0_mask[39])
      Memory[W0_addr][32'h27 +: 1] <= W0_data[39];
    if (W0_en & W0_mask[40])
      Memory[W0_addr][32'h28 +: 1] <= W0_data[40];
    if (W0_en & W0_mask[41])
      Memory[W0_addr][32'h29 +: 1] <= W0_data[41];
    if (W0_en & W0_mask[42])
      Memory[W0_addr][32'h2A +: 1] <= W0_data[42];
    if (W0_en & W0_mask[43])
      Memory[W0_addr][32'h2B +: 1] <= W0_data[43];
    if (W0_en & W0_mask[44])
      Memory[W0_addr][32'h2C +: 1] <= W0_data[44];
    if (W0_en & W0_mask[45])
      Memory[W0_addr][32'h2D +: 1] <= W0_data[45];
    if (W0_en & W0_mask[46])
      Memory[W0_addr][32'h2E +: 1] <= W0_data[46];
    if (W0_en & W0_mask[47])
      Memory[W0_addr][32'h2F +: 1] <= W0_data[47];
    if (W0_en & W0_mask[48])
      Memory[W0_addr][32'h30 +: 1] <= W0_data[48];
    if (W0_en & W0_mask[49])
      Memory[W0_addr][32'h31 +: 1] <= W0_data[49];
    if (W0_en & W0_mask[50])
      Memory[W0_addr][32'h32 +: 1] <= W0_data[50];
    if (W0_en & W0_mask[51])
      Memory[W0_addr][32'h33 +: 1] <= W0_data[51];
    if (W0_en & W0_mask[52])
      Memory[W0_addr][32'h34 +: 1] <= W0_data[52];
    if (W0_en & W0_mask[53])
      Memory[W0_addr][32'h35 +: 1] <= W0_data[53];
    if (W0_en & W0_mask[54])
      Memory[W0_addr][32'h36 +: 1] <= W0_data[54];
    if (W0_en & W0_mask[55])
      Memory[W0_addr][32'h37 +: 1] <= W0_data[55];
    if (W0_en & W0_mask[56])
      Memory[W0_addr][32'h38 +: 1] <= W0_data[56];
    if (W0_en & W0_mask[57])
      Memory[W0_addr][32'h39 +: 1] <= W0_data[57];
    if (W0_en & W0_mask[58])
      Memory[W0_addr][32'h3A +: 1] <= W0_data[58];
    if (W0_en & W0_mask[59])
      Memory[W0_addr][32'h3B +: 1] <= W0_data[59];
    if (W0_en & W0_mask[60])
      Memory[W0_addr][32'h3C +: 1] <= W0_data[60];
    if (W0_en & W0_mask[61])
      Memory[W0_addr][32'h3D +: 1] <= W0_data[61];
    if (W0_en & W0_mask[62])
      Memory[W0_addr][32'h3E +: 1] <= W0_data[62];
    if (W0_en & W0_mask[63])
      Memory[W0_addr][32'h3F +: 1] <= W0_data[63];
    if (W0_en & W0_mask[64])
      Memory[W0_addr][32'h40 +: 1] <= W0_data[64];
    if (W0_en & W0_mask[65])
      Memory[W0_addr][32'h41 +: 1] <= W0_data[65];
    if (W0_en & W0_mask[66])
      Memory[W0_addr][32'h42 +: 1] <= W0_data[66];
    if (W0_en & W0_mask[67])
      Memory[W0_addr][32'h43 +: 1] <= W0_data[67];
    if (W0_en & W0_mask[68])
      Memory[W0_addr][32'h44 +: 1] <= W0_data[68];
    if (W0_en & W0_mask[69])
      Memory[W0_addr][32'h45 +: 1] <= W0_data[69];
    if (W0_en & W0_mask[70])
      Memory[W0_addr][32'h46 +: 1] <= W0_data[70];
    if (W0_en & W0_mask[71])
      Memory[W0_addr][32'h47 +: 1] <= W0_data[71];
    if (W0_en & W0_mask[72])
      Memory[W0_addr][32'h48 +: 1] <= W0_data[72];
    if (W0_en & W0_mask[73])
      Memory[W0_addr][32'h49 +: 1] <= W0_data[73];
    if (W0_en & W0_mask[74])
      Memory[W0_addr][32'h4A +: 1] <= W0_data[74];
    if (W0_en & W0_mask[75])
      Memory[W0_addr][32'h4B +: 1] <= W0_data[75];
    if (W0_en & W0_mask[76])
      Memory[W0_addr][32'h4C +: 1] <= W0_data[76];
    if (W0_en & W0_mask[77])
      Memory[W0_addr][32'h4D +: 1] <= W0_data[77];
    if (W0_en & W0_mask[78])
      Memory[W0_addr][32'h4E +: 1] <= W0_data[78];
    if (W0_en & W0_mask[79])
      Memory[W0_addr][32'h4F +: 1] <= W0_data[79];
    if (W0_en & W0_mask[80])
      Memory[W0_addr][32'h50 +: 1] <= W0_data[80];
    if (W0_en & W0_mask[81])
      Memory[W0_addr][32'h51 +: 1] <= W0_data[81];
    if (W0_en & W0_mask[82])
      Memory[W0_addr][32'h52 +: 1] <= W0_data[82];
    if (W0_en & W0_mask[83])
      Memory[W0_addr][32'h53 +: 1] <= W0_data[83];
    if (W0_en & W0_mask[84])
      Memory[W0_addr][32'h54 +: 1] <= W0_data[84];
    if (W0_en & W0_mask[85])
      Memory[W0_addr][32'h55 +: 1] <= W0_data[85];
    if (W0_en & W0_mask[86])
      Memory[W0_addr][32'h56 +: 1] <= W0_data[86];
    if (W0_en & W0_mask[87])
      Memory[W0_addr][32'h57 +: 1] <= W0_data[87];
    if (W0_en & W0_mask[88])
      Memory[W0_addr][32'h58 +: 1] <= W0_data[88];
    if (W0_en & W0_mask[89])
      Memory[W0_addr][32'h59 +: 1] <= W0_data[89];
    if (W0_en & W0_mask[90])
      Memory[W0_addr][32'h5A +: 1] <= W0_data[90];
    if (W0_en & W0_mask[91])
      Memory[W0_addr][32'h5B +: 1] <= W0_data[91];
    if (W0_en & W0_mask[92])
      Memory[W0_addr][32'h5C +: 1] <= W0_data[92];
    if (W0_en & W0_mask[93])
      Memory[W0_addr][32'h5D +: 1] <= W0_data[93];
    if (W0_en & W0_mask[94])
      Memory[W0_addr][32'h5E +: 1] <= W0_data[94];
    if (W0_en & W0_mask[95])
      Memory[W0_addr][32'h5F +: 1] <= W0_data[95];
    if (W0_en & W0_mask[96])
      Memory[W0_addr][32'h60 +: 1] <= W0_data[96];
    if (W0_en & W0_mask[97])
      Memory[W0_addr][32'h61 +: 1] <= W0_data[97];
    if (W0_en & W0_mask[98])
      Memory[W0_addr][32'h62 +: 1] <= W0_data[98];
    if (W0_en & W0_mask[99])
      Memory[W0_addr][32'h63 +: 1] <= W0_data[99];
    if (W0_en & W0_mask[100])
      Memory[W0_addr][32'h64 +: 1] <= W0_data[100];
    if (W0_en & W0_mask[101])
      Memory[W0_addr][32'h65 +: 1] <= W0_data[101];
    if (W0_en & W0_mask[102])
      Memory[W0_addr][32'h66 +: 1] <= W0_data[102];
    if (W0_en & W0_mask[103])
      Memory[W0_addr][32'h67 +: 1] <= W0_data[103];
    if (W0_en & W0_mask[104])
      Memory[W0_addr][32'h68 +: 1] <= W0_data[104];
    if (W0_en & W0_mask[105])
      Memory[W0_addr][32'h69 +: 1] <= W0_data[105];
    if (W0_en & W0_mask[106])
      Memory[W0_addr][32'h6A +: 1] <= W0_data[106];
    if (W0_en & W0_mask[107])
      Memory[W0_addr][32'h6B +: 1] <= W0_data[107];
    if (W0_en & W0_mask[108])
      Memory[W0_addr][32'h6C +: 1] <= W0_data[108];
    if (W0_en & W0_mask[109])
      Memory[W0_addr][32'h6D +: 1] <= W0_data[109];
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 110'bx;
endmodule

