// Generated by CIRCT firtool-1.76.0

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ROB_entry_mem(	// src/main/scala/memories/memories.scala:295:7
  input        clock,	// src/main/scala/memories/memories.scala:295:7
  input  [5:0] io_addrA,	// src/main/scala/memories/memories.scala:296:14
  input        io_writeDataA_valid,	// src/main/scala/memories/memories.scala:296:14
               io_writeDataA_is_branch,	// src/main/scala/memories/memories.scala:296:14
  input  [1:0] io_writeDataA_memory_type,	// src/main/scala/memories/memories.scala:296:14
  input  [6:0] io_writeDataA_RD,	// src/main/scala/memories/memories.scala:296:14
  input        io_writeDataA_RD_valid,	// src/main/scala/memories/memories.scala:296:14
  input  [4:0] io_writeDataA_RDold,	// src/main/scala/memories/memories.scala:296:14
  input        io_writeEnableA,	// src/main/scala/memories/memories.scala:296:14
  input  [5:0] io_addrB,	// src/main/scala/memories/memories.scala:296:14
  output       io_readDataB_valid,	// src/main/scala/memories/memories.scala:296:14
               io_readDataB_is_branch,	// src/main/scala/memories/memories.scala:296:14
  output [1:0] io_readDataB_memory_type,	// src/main/scala/memories/memories.scala:296:14
  output [6:0] io_readDataB_RD,	// src/main/scala/memories/memories.scala:296:14
  output       io_readDataB_RD_valid,	// src/main/scala/memories/memories.scala:296:14
  output [4:0] io_readDataB_RDold	// src/main/scala/memories/memories.scala:296:14
);

  wire [16:0] _mem_ext_R0_data;	// src/main/scala/memories/memories.scala:310:24
  mem_64x17 mem_ext (	// src/main/scala/memories/memories.scala:310:24
    .R0_addr (io_addrB),
    .R0_en   (1'h1),	// src/main/scala/memories/memories.scala:295:7
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (io_addrA),
    .W0_en   (io_writeEnableA),
    .W0_clk  (clock),
    .W0_data
      ({io_writeDataA_RDold,
        io_writeDataA_RD_valid,
        io_writeDataA_RD,
        io_writeDataA_memory_type,
        io_writeDataA_is_branch,
        io_writeDataA_valid})	// src/main/scala/memories/memories.scala:310:24
  );	// src/main/scala/memories/memories.scala:310:24
  assign io_readDataB_valid = _mem_ext_R0_data[0];	// src/main/scala/memories/memories.scala:295:7, :310:24
  assign io_readDataB_is_branch = _mem_ext_R0_data[1];	// src/main/scala/memories/memories.scala:295:7, :310:24
  assign io_readDataB_memory_type = _mem_ext_R0_data[3:2];	// src/main/scala/memories/memories.scala:295:7, :310:24
  assign io_readDataB_RD = _mem_ext_R0_data[10:4];	// src/main/scala/memories/memories.scala:295:7, :310:24
  assign io_readDataB_RD_valid = _mem_ext_R0_data[11];	// src/main/scala/memories/memories.scala:295:7, :310:24
  assign io_readDataB_RDold = _mem_ext_R0_data[16:12];	// src/main/scala/memories/memories.scala:295:7, :310:24
endmodule

