// Generated by CIRCT firtool-1.76.0
module WAW_handler(	// src/main/scala/Frontend/rename.scala:39:7
  input        io_decoder_RD_valid_bits_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_valid_bits_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_valid_bits_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_valid_bits_3,	// src/main/scala/Frontend/rename.scala:47:16
  input  [4:0] io_decoder_RD_values_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_values_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_values_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_decoder_RD_values_3,	// src/main/scala/Frontend/rename.scala:47:16
  input  [6:0] io_free_list_RD_values_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_free_list_RD_values_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_free_list_RD_values_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_free_list_RD_values_3,	// src/main/scala/Frontend/rename.scala:47:16
  output       io_RAT_wr_en_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_wr_en_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_wr_en_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_wr_en_3,	// src/main/scala/Frontend/rename.scala:47:16
  output [4:0] io_RAT_RD_values_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_RD_values_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_RD_values_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_RAT_RD_values_3,	// src/main/scala/Frontend/rename.scala:47:16
  output [6:0] io_FL_RD_values_0,	// src/main/scala/Frontend/rename.scala:47:16
               io_FL_RD_values_1,	// src/main/scala/Frontend/rename.scala:47:16
               io_FL_RD_values_2,	// src/main/scala/Frontend/rename.scala:47:16
               io_FL_RD_values_3	// src/main/scala/Frontend/rename.scala:47:16
);

  assign io_RAT_wr_en_0 =
    io_decoder_RD_valid_bits_0
    & (io_decoder_RD_values_0 != io_decoder_RD_values_1 | ~io_decoder_RD_valid_bits_1)
    & (io_decoder_RD_values_0 != io_decoder_RD_values_2 | ~io_decoder_RD_valid_bits_2)
    & (io_decoder_RD_values_0 != io_decoder_RD_values_3 | ~io_decoder_RD_valid_bits_3);	// src/main/scala/Frontend/rename.scala:39:7, :69:{33,62,91,94}
  assign io_RAT_wr_en_1 =
    io_decoder_RD_valid_bits_1
    & (io_decoder_RD_values_1 != io_decoder_RD_values_2 | ~io_decoder_RD_valid_bits_2)
    & (io_decoder_RD_values_1 != io_decoder_RD_values_3 | ~io_decoder_RD_valid_bits_3);	// src/main/scala/Frontend/rename.scala:39:7, :69:{33,62,91,94}
  assign io_RAT_wr_en_2 =
    io_decoder_RD_valid_bits_2
    & (io_decoder_RD_values_2 != io_decoder_RD_values_3 | ~io_decoder_RD_valid_bits_3);	// src/main/scala/Frontend/rename.scala:39:7, :69:{33,62,91,94}
  assign io_RAT_wr_en_3 = io_decoder_RD_valid_bits_3;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_RAT_RD_values_0 = io_decoder_RD_values_0;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_RAT_RD_values_1 = io_decoder_RD_values_1;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_RAT_RD_values_2 = io_decoder_RD_values_2;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_RAT_RD_values_3 = io_decoder_RD_values_3;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_FL_RD_values_0 = io_free_list_RD_values_0;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_FL_RD_values_1 = io_free_list_RD_values_1;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_FL_RD_values_2 = io_free_list_RD_values_2;	// src/main/scala/Frontend/rename.scala:39:7
  assign io_FL_RD_values_3 = io_free_list_RD_values_3;	// src/main/scala/Frontend/rename.scala:39:7
endmodule

