title: ChaosCore
theme: just-the-docs


# Set the base URL to match your repository name
baseurl: "/ChaosCore" # The subpath of your site, e.g., /repository-name
url: "https://hakamtassi.github.io" # The base hostname & protocol for your site

# Auxiliary links for your site (update or remove as needed)
aux_links:
  Project Repository: https://github.com/hakamtassi/ChaosCore

#color_scheme: dark
color_scheme: theme

callouts_level: loud
callouts:
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Include necessary folders
include:
  - _pages
  - Core Architecture
  - Regression
  - building

sass:
  quiet_deps: true