title: ChaosCore
description: A security oriented Chess playing SoC.
theme: just-the-docs

# Set the base URL to match your repository name
baseurl: "/ChaosCoredocs" # The subpath of your site, e.g., /repository-name
url: "https://hakatassi.github.io" # The base hostname & protocol for your site

# Auxiliary links for your site
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

# Include necessary folders
include:
  - _pages
  - Core Architecture
  - DTA
  - verification
  - extensions
  - building
