name: Run test suite

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #- uses: actions/checkout@v1
      #- name: Build Docker Image
        #run: docker build -t ChaosCore .

      # Run tests using pytest inside Docker container
      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/root/cocotb/frontend/rename:/work ChaosCore pytest
