#name: Run test suite

#on:
  #push:

#jobs:
  #build:
    #runs-on: ubuntu-latest

    #steps:
      #- uses: actions/checkout@v1
      #- name: Build Docker Image
        #run: docker build -t ChaosCore .

name: Run test suite

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.docker \
            --cache-to=type=local,dest=/tmp/.docker \
            -t ChaosCore .
      
      # Run tests using pytest inside Docker container
      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/root/cocotb/frontend/rename:/work ChaosCore pytest
