#name: Run test suite

#on:
  #push:

#jobs:
  #build:
    #runs-on: ubuntu-latest

    #steps:
      #- uses: actions/checkout@v3
      #- uses: docker/setup-buildx-action@v3
      #- uses: docker/build-push-action@v5
        #with:
          #context: .
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          ##repository: chaoscore
          #tags: chaoscore:latest  # Set the image name and tag here

      ## Run tests using pytest inside Docker container
      #- name: Run tests
        #run: |
          #docker run --rm -v $(pwd)/root/cocotb/frontend/rename:/work chaoscore pytest


name: Run test suite

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: chaoscore:latest

      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/root/cocotb/frontend/rename:/work chaoscore pytest
