# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

build:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: docs

- name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.1'
      bundler-cache: true
      cache-version: 0
      working-directory: '${{ github.workspace }}/docs'

- name: Upload artifact
    uses: actions/upload-pages-artifact@v1
    with:
      path: "docs/_site/"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"